# Generated by Django 3.2.5 on 2021-07-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('number', models.IntegerField(max_length=30, null=True)),
                ('message', models.TextField(max_length=150)),
            ],
        ),
    ]
